### ISSUE TITLE
OutOfRangeException on app start

### ISSUE THREAD

**Issue by slimshader** [JamesnetGroup/leagueoflegends-wpf#6]
Hi,

when trying to run fresh pull of main branch, getting OutOfRangeException in MainContent.cs line 9

**Comment by jamesnet214** [comment]
@slimshader The issue has been resolved and everything is working fine now. Would you like to delete the repository, clone it again, and retest?

**Comment by slimshader** [comment]
I am not sure what you mean by resolved, I don't see any new commits since I posted the issue?

Anyway, I cloned repo again but problem still exists.

**Comment by jamesnet214** [comment]
@slimshader 

There's a possibility that your environment might be the issue.

Please provide the following information:
Operating System:
Visual Studio version:
.NET version:

Also, occasionally problems are occurring with the Visual Studio Preview version.
https://github.com/dotnet/wpf/pull/9584

![image](https://github.com/user-attachments/assets/525a097d-5b93-4d8b-b0ae-61a9c4733014)

**Comment by slimshader** [comment]
Indeed, it was VS 2022 Preview issue, updated to the latest (17.12.0 Preview 2.0) and works like a charm. Thanks!
